#ifndef __HYPERWIN_STATUS_H_
#define __HYPERWIN_STATUS_H_

/* HyperWin status codes */

#define HYPERWIN_OFFSET				    1000

#define HYPERWIN_STATUS_SUCCUESS        (0 + HYPERWIN_OFFSET)
#define HYPERWIN_INIT_FAILED            (1 + HYPERWIN_OFFSET)
#define HYPERWIN_IOCTL_FAILED           (2 + HYPERWIN_OFFSET)
#define HYPERWIN_CREATE_FAILED          (3 + HYPERWIN_OFFSET)
#define HYPERWIN_CREATE_WINDOW_FAILED   (4 + HYPERWIN_OFFSET)
#define HYPERWIN_PROCESS_NOT_FOUND      (5 + HYPERWIN_OFFSET)
#define HYPERWIN_LIBRARY_NOT_FOUND      (6 + HYPERWIN_OFFSET)
#define HYPERWIN_UNKNOWN_ENCODING_TYPE  (7 + HYPERWIN_OFFSET)
#define HYPERWIN_PARSING_ERROR		    (8 + HYPERWIN_OFFSET)
#define HYPERWIN_ALLOCATION_ERROR	    (9 + HYPERWIN_OFFSET)
#define HYPERWIN_EXIT				    (10 + HYPERWIN_OFFSET)
#define HYPERWIN_UNKNOWN_COMMAND        (11 + HYPERWIN_OFFSET)
#define HYPERWIN_INVALID_HANDLE         (12 + HYPERWIN_OFFSET)
#define HYPERWIN_FILE_NOT_FOUND         (13 + HYPERWIN_OFFSET)
#define HYPERWIN_PATH_MUST_BE_SPECIFIED (14 + HYPERWIN_OFFSET)
#define HYPERWIN_UNKNOWN_OPERATION      (15 + HYPERWIN_OFFSET)
#define HYPERWIN_QUERY_INFO_FAILED      (16 + HYPERWIN_OFFSET)

#endif