#ifndef __HYPERWIN_STATUS_H_
#define __HYPERWIN_STATUS_H_

/* HyperWin status codes */

#define HYPERWIN_STATUS_SUCCUESS      0
#define HYPERWIN_INIT_FAILED          1
#define HYPERWIN_IOCTL_FAILED         2
#define HYPERWIN_CREATE_FAILED        3
#define HYPERWIN_CREATE_WINDOW_FAILED 4
#define HYPERWIN_PROCESS_NOT_FOUND    5
#define HYPERWIN_LIBRARY_NOT_FOUND    6

#endif